--- #YAML:1.0
name:                Tk-HyperText
version:             0.11
abstract:            An ROText widget which renders HTML code.
license:             ~
author:
    - Noah Petherbridge <kirsle@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:
    HTML::TokeParser: 0
    Tk::Derived: 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
